###############################################################################
## MS-499 — Marine Fish Marketing System of Chattogram, Bangladesh
## COMPLETE, SELF-CONTAINED ANALYSIS SCRIPT FOR R
##
## HOW TO RUN (R console / RStudio) ----------------------------------------
##   1. Put this script and the data workbook in the SAME folder.
##   2. In the R console:
##          setwd("path/to/that/folder")
##          source("MS499_full_analysis.R")
##      Or simply:  Rscript MS499_full_analysis.R
##   3. One-off package install (internet needed once):
##          install.packages(c("readxl", "openxlsx"))
##
## Tested against R 4.x (base R only -- NO dplyr / tidyr / ggplot2 needed,
## so it runs on a stock R installation). Charts use base graphics.
##
## At the end it prints a VERIFICATION REPORT: every table with its row and
## column count, the reproducibility checks, and the three accounting gates.
## Everything it writes lands in a new folder "analysis_outputs_r/".
##
## Produces, from the filled data workbook only:
##   T1  Respondent profile                 T11 Retail price by species x market
##   T2  Business scale                     T12 Matched-pair detail
##   T2b Channel patterns                   T12b Wilcoxon signed-rank
##   T3  Price chain by species             T13 Species x market spread
##   T4  Marketing costs (itemised)         T14 Kruskal-Wallis by species
##   T4b Marketing cost per kg              T14b Dunn post-hoc (Holm)
##   T5  Payment methods                    T15 Payment mode x actor chi-square
##   T6  Marketing problems                 T16 Stratum margins + Mann-Whitney
##   T7  Market infrastructure              T17 Cost-profit (Spearman)
##   T8  Consumer behaviour                 T18 Shapiro-Wilk normality screen
##   T9  Other aquatic products             T19 Channel-level indicators
##   T10 Margins and producer's share           (spread, GMM, NMM, PS, ME)
##
## Every rule below mirrors scripts/run_analysis.py and
## scripts/extend_analysis.py exactly, so the two engines agree cell-for-cell.
## Methodology references are to Methodology V4 (01_source_pdfs/).
##
## DATA PROVENANCE — READ BEFORE CITING
## The default input is SYNTHETIC: generated by
## scripts/generate_synthetic_data.py from random.Random(20260315). It is a
## pipeline-validation dataset, NOT observed field data. If you collect real
## data, point INPUT_FILE at it (below) and re-run; nothing else changes.
###############################################################################

## ---------------------------------------------------------------- CONFIG ----
## Data workbook. Leave as-is for the shipped dataset; for real field data
## put your filled workbook next to this script and set its file name here
## (or set INPUT_FILE <- "" to auto-detect the only .xlsx in the folder).
INPUT_FILE  <- "MS499_Chattogram_Marine_Fish_Data.xlsx"
OUTPUT_DIR  <- "analysis_outputs_r"   ## created automatically if missing
MAKE_CHARTS <- TRUE                   ## set FALSE for tables only

## --- locate the workbook, so source() works from any working directory ------
.locate <- function(cand) {
  if (cand != "" && file.exists(cand)) return(cand)
  here <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)),
                   error = function(e) getwd())
  if (!is.null(here) && !is.na(here)) {
    for (t in c(file.path(here, basename(cand)), file.path(here, cand)))
      if (file.exists(t)) return(t)
  }
  for (t in c(file.path(getwd(), basename(cand)), file.path(getwd(), cand)))
    if (file.exists(t)) return(t)
  for (d in unique(c(if (!is.null(here)) here else NA, getwd()))) {
    if (is.na(d) || !dir.exists(d)) next
    x <- list.files(d, pattern = "\\.xlsx$", full.names = TRUE, ignore.case = TRUE)
    x <- x[!grepl("(~\\$|Analysis_Summary)", x)]
    if (length(x) == 1) return(x)
    if (length(x) > 1) {
      hit <- grep("MS499|Chattogram|Filled|Data", x, ignore.case = TRUE, value = TRUE)
      if (length(hit) >= 1) return(hit[1])
    }
  }
  cand
}
INPUT_FILE <- .locate(INPUT_FILE)
if (!file.exists(INPUT_FILE))
  stop("\nData workbook not found. Put the .xlsx in the same folder as this ",
       "script,\nor set INPUT_FILE (line ~44) to the full path.\n")

MAUND         <- 37.32          ## 1 maund = 37.32 kg (Methodology 3.2)
LANDING       <- c("M1", "M6")  ## landing-linked markets (Methodology 3.11c)
MIN_CONS      <- 3              ## min consumer slips before a share is reported
MIN_MARKETS   <- 3              ## Methodology 3.8: <3 markets => descriptive only
TRADING_DAYS_MONTH <- 26        ## cost normalisation
TRADING_DAYS_YEAR  <- 312
ALPHA         <- 0.05

## --------------------------------------------------------------- PACKAGES ---
need <- c("readxl", "openxlsx")
missing_pkgs <- need[!vapply(need, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing_pkgs))
  stop("\nMissing R package(s): ", paste(missing_pkgs, collapse = ", "),
       "\nInstall them once with:\n    install.packages(c(",
       paste(sprintf("\"%s\"", missing_pkgs), collapse = ", "), "))\n")
suppressPackageStartupMessages({ library(readxl); library(openxlsx) })
HAVE_GGPLOT <- requireNamespace("ggplot2", quietly = TRUE)

## ---------------------------------------------------------------- HELPERS ---
`%||%` <- function(a, b) if (is.null(a) || length(a) == 0) b else a

read_sheet <- function(sheet, id_col = NULL) {
  ## Template sheets carry their header on row 4 and data from row 5.
  df <- as.data.frame(readxl::read_excel(INPUT_FILE, sheet = sheet, skip = 3,
                                         .name_repair = "unique"))
  if (!is.null(id_col) && id_col %in% names(df)) {
    df <- df[!is.na(df[[id_col]]) & as.character(df[[id_col]]) != "", , drop = FALSE]
  } else {
    df <- df[rowSums(is.na(df)) < ncol(df), , drop = FALSE]
  }
  df
}

as_num <- function(x) suppressWarnings(as.numeric(as.character(x)))

## BDT per kg, with fallback recomputation from the raw quote (Methodology 3.2)
ppk <- function(raw, unit, cached) {
  v <- as_num(cached)
  out <- ifelse(!is.na(v), round(v, 2), NA_real_)
  r <- as_num(raw)
  u <- tolower(as.character(unit))
  fb <- ifelse(!is.na(r),
               ifelse(!is.na(u) & u == "maund", round(r / MAUND, 2), round(r, 2)),
               NA_real_)
  ifelse(is.na(out), fb, out)
}

## quantity in kg, with fallback (maund -> kg multiplies)
qkg <- function(raw, unit, cached) {
  v <- as_num(cached)
  out <- ifelse(!is.na(v), round(v, 2), NA_real_)
  r <- as_num(raw)
  u <- tolower(as.character(unit))
  fb <- ifelse(!is.na(r),
               ifelse(!is.na(u) & u == "maund", round(r * MAUND, 2), round(r, 2)),
               NA_real_)
  ifelse(is.na(out), fb, out)
}

## bind data frames that do not share all columns, on their intersection
rbind_common <- function(lst) {
  cn <- Reduce(intersect, lapply(lst, names))
  do.call(rbind, lapply(lst, function(d) d[, cn, drop = FALSE]))
}

mean_sd <- function(x, nd = 2) {
  x <- x[!is.na(x)]
  if (!length(x)) return(c(NA, NA, 0))
  c(round(mean(x), nd),
    if (length(x) > 1) round(sd(x), nd) else 0,
    length(x))
}

pct <- function(k, n, nd = 1) if (!n) 0 else round(100 * k / n, nd)

## convert a mixed-frequency cost item to BDT per trading day
per_day <- function(amount, freq, default_days = 1) {
  v <- as_num(amount)
  if (is.na(v) || v <= 0) return(0)
  f <- tolower(as.character(freq)); f <- ifelse(is.na(f), "", f)
  if (grepl("^day", f)) v
  else if (grepl("^month", f)) v / TRADING_DAYS_MONTH
  else if (grepl("^year", f) || grepl("^annual", f)) v / TRADING_DAYS_YEAR
  else if (grepl("^week", f)) v / 6
  else v / default_days
}

mkdir <- function(p) { if (!dir.exists(p)) dir.create(p, recursive = TRUE); p }

## ------------------------------------------------------------- LOAD DATA ----
cat("Reading:", INPUT_FILE, "\n")
SP   <- read_sheet("Codebook_Species")
MK   <- read_sheet("Codebook_Markets")
## Forms carry 36 pre-allocated ID rows (30 quota + 6 spare); keep only rows
## with an interview date, which is what makes a row a real respondent.
read_form <- function(sheet) {
  d <- read_sheet(sheet)
  d[!is.na(d$Interview_Date) & as.character(d$Interview_Date) != "", , drop = FALSE]
}
FA   <- read_form("Form_A_Aratdar")
FB   <- read_form("Form_B_Bepari_Faria")
FR   <- read_form("Form_R_Khuchra")
FC   <- read_form("Form_C_Consumer")
PO   <- read_sheet("Price_Observations",  "Respondent_ID")
CPF  <- read_sheet("Consumer_Purchases_Focal")
COF  <- read_sheet("Consumer_Other_Fish", "Fish_name_local")
FM   <- read_sheet("Form_M_Market_Observation", "Obs_Date")

SP_CODES <- as.character(SP$Code); SP_CODES <- SP_CODES[!is.na(SP_CODES)]
MK_CODES <- as.character(MK$Code); MK_CODES <- MK_CODES[!is.na(MK_CODES)]
MK_NAME  <- setNames(as.character(MK$Market_name), as.character(MK$Code))
SP_LOCAL <- setNames(as.character(SP$Local_name),  as.character(SP$Code))

PO$buy_kg  <- ppk(PO$Buy_price_raw,  PO$Unit, PO$Buy_BDT_per_kg)
PO$sell_kg <- ppk(PO$Sell_price_raw, PO$Unit, PO$Sell_BDT_per_kg)
PO$qty_kg  <- qkg(PO$Quantity_raw,   PO$Quantity_unit, PO$Quantity_kg)
CPF$price_kg <- ppk(CPF$Price_raw, CPF$Unit, CPF$Price_BDT_per_kg)
CPF$qty_kg   <- qkg(CPF$Quantity_raw, CPF$Quantity_unit, CPF$Quantity_kg)
COF$price_kg <- ppk(COF$Price_raw, COF$Unit, COF$Price_BDT_per_kg)
CPF$Species_code <- as.character(CPF$Species_code)
CPF$Purchased_today <- as.character(CPF$Purchased_today)
CPFY <- CPF[!is.na(CPF$Purchased_today) & CPF$Purchased_today == "Yes", , drop = FALSE]

cat(sprintf("Loaded: A=%d B=%d R=%d C=%d  price_obs=%d purchases=%d\n",
            nrow(FA), nrow(FB), nrow(FR), nrow(FC), nrow(PO), nrow(CPFY)))

## mean price by actor / species / market -------------------------------------
po_mean <- function(actor, field, species = NULL, markets = NULL) {
  d <- PO[PO$Actor_type == actor, , drop = FALSE]
  if (!is.null(species)) d <- d[as.character(d$Species_code) == species, , drop = FALSE]
  if (!is.null(markets)) d <- d[as.character(d$Market) %in% markets, , drop = FALSE]
  v <- d[[field]]; v <- v[!is.na(v)]
  if (!length(v)) NA_real_ else round(mean(v), 2)
}
cons_mean <- function(species) {
  v <- CPFY$price_kg[as.character(CPFY$Species_code) == species]
  v <- v[!is.na(v)]
  if (!length(v)) NA_real_ else round(mean(v), 2)
}
cons_n <- function(species)
  sum(as.character(CPFY$Species_code) == species & !is.na(CPFY$price_kg))

ret_markets <- function(species) {
  d <- PO[PO$Actor_type == "Khuchra" & as.character(PO$Species_code) == species &
            !is.na(PO$sell_kg), , drop = FALSE]
  unique(as.character(d$Market))
}

TABLES <- list()   ## name -> list(df, title, note)

## ============================ T1  Respondent profile =========================
profile_row <- function(label, rs) {
  if (!nrow(rs)) return(NULL)
  edu <- table(factor(as.character(rs$Education),
                      levels = c("Illiterate", "Primary", "Secondary",
                                 "Higher_Secondary")))
  n <- nrow(rs)
  data.frame(Actor = label, n = n,
             Age_mean_years      = round(mean(as_num(rs$Age_years), na.rm = TRUE), 2),
             Age_sd_years        = round(sd(as_num(rs$Age_years), na.rm = TRUE), 2),
             Years_in_business_mean = round(mean(as_num(rs$Years_in_business), na.rm = TRUE), 2),
             Years_in_business_sd   = round(sd(as_num(rs$Years_in_business), na.rm = TRUE), 2),
             Family_size_mean    = round(mean(as_num(rs$Family_members), na.rm = TRUE), 2),
             Edu_Illiterate_pct     = pct(edu[["Illiterate"]], n),
             Edu_Primary_pct        = pct(edu[["Primary"]], n),
             Edu_Secondary_pct      = pct(edu[["Secondary"]], n),
             `Edu_Higher Secondary_pct` = pct(edu[["Higher_Secondary"]], n),
             check.names = FALSE,
             stringsAsFactors = FALSE)
}
T1 <- rbind(
  profile_row("Aratdar", FA),
  profile_row("Bepari",  FB[as.character(FB$Actor_subtype) == "Bepari", , drop = FALSE]),
  profile_row("Faria",   FB[as.character(FB$Actor_subtype) == "Faria",  , drop = FALSE]),
  profile_row("Retailer", FR),
  profile_row("All traders", rbind_common(list(FA, FB, FR)))
)
TABLES[["T1_Respondent_Profile"]] <- list(
  df = T1, title = "Table 1. Socio-economic profile of respondents",
  note = "Means and SD of age, years in business and family size by actor group; education as % of the group.")

## ============================ T2  Business scale =============================
scale_row <- function(label, rs) {
  if (!nrow(rs)) return(NULL)
  v <- as_num(rs$Daily_capacity_kg); v <- v[!is.na(v)]
  data.frame(Actor = label, n = length(v),
             Daily_capacity_kg_mean   = round(mean(v), 2),
             Daily_capacity_kg_sd     = round(sd(v), 2),
             Daily_capacity_kg_median = round(median(v), 1),
             Daily_capacity_kg_min    = round(min(v), 1),
             Daily_capacity_kg_max    = round(max(v), 1),
             stringsAsFactors = FALSE)
}
T2 <- rbind(scale_row("Aratdar", FA), scale_row("Bepari/Faria", FB),
            scale_row("Retailer", FR))
T2$Workers_mean <- c(round(mean(as_num(FA$Workers_count), na.rm = TRUE), 2), NA, NA)
T2$Worker_wage_BDT_day_mean <- c(round(mean(as_num(FA$Worker_daily_wage_BDT), na.rm = TRUE), 2), NA, NA)
T2$Trips_per_period_mean <- c(NA, round(mean(as_num(FB$Trips_per_period), na.rm = TRUE), 2), NA)
T2$Ice_use_kg_day_mean   <- c(NA, round(mean(as_num(FB$Ice_usage_kg_per_day), na.rm = TRUE), 2), NA)
T2$Spoilage_pct_mean     <- c(NA, NA, round(mean(as_num(FR$Spoilage_pct), na.rm = TRUE), 2))
TABLES[["T2_Business_Scale"]] <- list(
  df = T2, title = "Table 2. Business scale of trading actors",
  note = "Daily traded/handled volume per actor group (kg/day).")

## ============================ T2b Channel patterns ===========================
## Counter.most_common() equivalent: count descending, ties in first-appearance order
most_common <- function(x) {
  x <- as.character(x); x <- x[!is.na(x) & x != ""]
  u <- unique(x)                                   ## first-appearance order
  n <- vapply(u, function(k) sum(x == k), integer(1))
  ord <- order(-n, seq_along(u))                   ## count desc, ties keep order
  list(keys = u[ord], n = as.integer(n[ord]), total = length(x))
}
chan <- function(form, field, fixed_order = NULL) {
  mc <- most_common(if (form == "B") FB[[field]] else FR[[field]])
  keys <- if (!is.null(fixed_order)) fixed_order else mc$keys
  ns <- setNames(mc$n, mc$keys)
  ## A fixed order is reported in full: a category with zero observations is
  ## still shown (n = 0), which is what makes "no retailer sells entirely on
  ## cash" a visible result rather than a silent omission.
  ns <- vapply(keys, function(k) if (k %in% names(ns)) ns[[k]] else 0L, integer(1))
  data.frame(Form = if (form == "B") "Form B (Bepari/Faria)" else "Form R (Retailer)",
             Field = gsub("_", " ", field), Value = keys,
             n = as.integer(ns), pct = pct(as.integer(ns), mc$total),
             stringsAsFactors = FALSE)
}
CREDIT_ORDER <- c("Almost_all", "Some", "None")
T2b <- rbind(chan("B", "Actor_subtype"), chan("B", "Business_pattern"),
             chan("B", "Supplier_category"), chan("B", "Source_location"),
             chan("B", "Credit_sales_share", CREDIT_ORDER),
             chan("R", "Buys_from"), chan("R", "Sells_to"),
             chan("R", "Sells_on_credit", CREDIT_ORDER))
TABLES[["T2b_Channel_Patterns"]] <- list(
  df = T2b, title = "Table 2b. Channel structure and trading patterns",
  note = "Percentages are within the actor group (n=30 each).")

## ============================ T3  Price chain ================================
t3_rows <- list()
for (code in SP_CODES) {
  nmk  <- length(ret_markets(code)); cn <- cons_n(code)
  prod <- po_mean("Aratdar", "buy_kg",  code, LANDING)
  arat <- po_mean("Aratdar", "sell_kg", code, LANDING)
  bep  <- po_mean("Bepari_Faria", "sell_kg", code)
  ret  <- po_mean("Khuchra", "sell_kg", code)
  cons <- cons_mean(code)
  complete <- all(!is.na(c(prod, arat, bep, cons))) &&
    cn >= MIN_CONS && nmk >= MIN_MARKETS
  reasons <- c()
  if (nmk < MIN_MARKETS) reasons <- c(reasons, sprintf("retail quotes in %d market(s)", nmk))
  if (cn == 0) reasons <- c(reasons, "no consumer quotes")
  else if (cn < MIN_CONS) reasons <- c(reasons,
      sprintf("consumer quotes n=%d (<%d; share not reported)", cn, MIN_CONS))
  dif <- function(a, b) if (is.na(a) || is.na(b)) NA_real_ else round(a - b, 2)
  t3_rows[[code]] <- data.frame(
    Species_code = code, Local_name = SP_LOCAL[[code]],
    English_name = as.character(SP$English_common_name[as.character(SP$Code) == code]),
    n_price_obs = sum(as.character(PO$Species_code) == code &
                        (!is.na(PO$buy_kg) | !is.na(PO$sell_kg))),
    Retail_markets_n = nmk, Consumer_paid_n = cn,
    Reporting_status = if (length(reasons))
      paste0("Descriptive-only (Method 3.8): ", paste(reasons, collapse = "; ")) else "",
    Producer_BDT_kg = prod, Aratdar_sell_BDT_kg = arat,
    Bepari_sell_BDT_kg = bep, Retailer_sell_BDT_kg = ret,
    Consumer_paid_BDT_kg = cons,
    Aratdar_margin_BDT_kg  = if (complete) dif(arat, prod) else NA_real_,
    Bepari_margin_BDT_kg   = if (complete) dif(bep, arat)  else NA_real_,
    Retailer_margin_BDT_kg = if (complete) dif(cons, bep)  else NA_real_,
    Total_spread_BDT_kg    = if (complete) dif(cons, prod) else NA_real_,
    Producer_share_pct     = if (complete) round(100 * prod / cons, 1) else NA_real_,
    stringsAsFactors = FALSE)
}
T3 <- do.call(rbind, t3_rows)
full <- T3[!is.na(T3$Total_spread_BDT_kg), , drop = FALSE]
codes_all <- as.character(full$Species_code)
mof <- function(f) round(mean(full[[f]], na.rm = TRUE), 2)
T3 <- rbind(T3, data.frame(
  Species_code = "ALL",
  Local_name = paste0("Mean of species means (chain-complete: ",
                      paste(codes_all, collapse = ", "), ")"),
  English_name = "-",
  n_price_obs = sum(as.character(PO$Species_code) %in% codes_all &
                      (!is.na(PO$buy_kg) | !is.na(PO$sell_kg))),
  Retail_markets_n = NA, Consumer_paid_n = NA,
  Reporting_status = sprintf("Pooled over %d chain-complete species (consumer n >= %d)",
                             nrow(full), MIN_CONS),
  Producer_BDT_kg = mof("Producer_BDT_kg"), Aratdar_sell_BDT_kg = mof("Aratdar_sell_BDT_kg"),
  Bepari_sell_BDT_kg = mof("Bepari_sell_BDT_kg"), Retailer_sell_BDT_kg = mof("Retailer_sell_BDT_kg"),
  Consumer_paid_BDT_kg = mof("Consumer_paid_BDT_kg"),
  Aratdar_margin_BDT_kg = round(mof("Aratdar_sell_BDT_kg") - mof("Producer_BDT_kg"), 2),
  Bepari_margin_BDT_kg = round(mof("Bepari_sell_BDT_kg") - mof("Aratdar_sell_BDT_kg"), 2),
  Retailer_margin_BDT_kg = round(mof("Consumer_paid_BDT_kg") - mof("Bepari_sell_BDT_kg"), 2),
  Total_spread_BDT_kg = round(mof("Consumer_paid_BDT_kg") - mof("Producer_BDT_kg"), 2),
  Producer_share_pct = round(100 * mof("Producer_BDT_kg") / mof("Consumer_paid_BDT_kg"), 1),
  stringsAsFactors = FALSE))
TABLES[["T3_Price_Chain"]] <- list(
  df = T3, title = "Table 3. Price chain by species (BDT per kg)",
  note = paste0("Producer = Form A buy at landing-linked M1/M6 (first-sale proxy, Method 3.11c); ",
    "Aratdar sell = auction hammer price at M1/M6; Bepari sell = Form B over all markets; ",
    "Retailer sell = Form R vendor quote (descriptive); Consumer = focal purchases paid (Form C). ",
    "Margins are differences of consecutive level means and telescope to the total spread. ",
    "Chain-complete requires all four levels, >= ", MIN_CONS, " consumer slips AND retail quotes ",
    "in >= ", MIN_MARKETS, " markets (Method 3.8); other species are descriptive-only."))

## ============================ T4  Marketing costs ============================
cost_row <- function(actor, item, unit, values, note = "") {
  v <- as_num(values); v <- v[!is.na(v)]
  if (!length(v)) return(NULL)
  data.frame(Actor = actor, Cost_item = item, Unit = unit, n = length(v),
             Mean = round(mean(v), 2),
             SD = if (length(v) > 1) round(sd(v), 2) else 0,
             Note = note, stringsAsFactors = FALSE)
}
T4 <- rbind(
  cost_row("Aratdar", "Commission rate", "% of lot value",
           FA$Commission_rate[as.character(FA$Commission_basis) == "Percent"],
           "Percent-basis aratdars only"),
  cost_row("Aratdar", "Arat/office rent (yearly payers)", "BDT per year",
           FA$Rent_amount_BDT[as.character(FA$Rent_frequency) == "Yearly"]),
  cost_row("Aratdar", "Arat/office rent (monthly payers)", "BDT per month",
           FA$Rent_amount_BDT[as.character(FA$Rent_frequency) == "Monthly"]),
  cost_row("Aratdar", "Electricity bill (monthly payers)", "BDT per month",
           FA$Electricity_bill_BDT[as.character(FA$Electricity_frequency) == "Monthly"]),
  cost_row("Aratdar", "Electricity bill (yearly payers)", "BDT per year",
           FA$Electricity_bill_BDT[as.character(FA$Electricity_frequency) == "Yearly"]),
  cost_row("Aratdar", "Workers employed", "persons", FA$Workers_count, "Own/family + hired"),
  cost_row("Aratdar", "Worker daily wage", "BDT per day", FA$Worker_daily_wage_BDT),
  cost_row("Aratdar", "Equipment & cooler maintenance (yearly)", "BDT per year",
           FA$Equipment_Cooler_Maintenance_BDT[
             as.character(FA$Equipment_Cooler_Maintenance_frequency) == "Yearly"]),
  cost_row("Aratdar", "Other operating cost", "BDT per period", FA$Other_cost_BDT,
           "See Other_cost_description in Form A"),
  cost_row("Bepari/Faria", "Transport fare per trip", "BDT per trip", FB$Transport_fare_per_trip_BDT),
  cost_row("Bepari/Faria", "Trips per period", "trips", FB$Trips_per_period),
  cost_row("Bepari/Faria", "Loading/unloading cost", "BDT per trip", FB$Loading_Unloading_cost_per_trip_BDT),
  cost_row("Bepari/Faria", "Ice usage", "kg per day", FB$Ice_usage_kg_per_day),
  cost_row("Bepari/Faria", "Ice cost", "BDT per day", FB$Ice_cost_BDT_per_day),
  cost_row("Bepari/Faria", "Commission paid to aratdar (percent basis)", "% of lot",
           FB$Commission_to_aratdar_value[as.character(FB$Commission_unit) == "Percent_of_lot"]),
  cost_row("Bepari/Faria", "Commission paid to aratdar (flat basis)", "BDT per lot",
           FB$Commission_to_aratdar_value[as.character(FB$Commission_unit) != "Percent_of_lot" & !is.na(FB$Commission_unit)]),
  cost_row("Bepari/Faria", "Transit damage/loss", "% of lot", FB$Transit_damage_pct),
  cost_row("Retailer", "Shop/van rent", "BDT per day", FR$Shop_Van_Rent_BDT_per_day),
  cost_row("Retailer", "Ice cost", "BDT per day", FR$Ice_cost_BDT_per_day),
  cost_row("Retailer", "Washing, water & other", "BDT per day", FR$Wash_Water_Other_cost_BDT_per_day),
  cost_row("Retailer", "Spoilage/unsold loss", "% of purchase", FR$Spoilage_pct)
)
TABLES[["T4_Marketing_Costs"]] <- list(
  df = T4, title = "Table 4. Itemised marketing costs by actor",
  note = "Itemised cash expenses as reported; frequencies differ by item (see Unit column).")

## ============================ T4b Marketing cost per kg ======================
## Methodology 3.7.1: MC = sum of itemised expenses / quantity per day.
resp_buy_px <- function(rid) {
  v <- PO$buy_kg[as.character(PO$Respondent_ID) == rid]; v <- v[!is.na(v)]
  if (!length(v)) NA_real_ else mean(v)
}
mc_aratdar <- function() {
  cap <- as_num(FA$Daily_capacity_kg)
  rent  <- mapply(per_day, FA$Rent_amount_BDT, FA$Rent_frequency)
  elec  <- mapply(per_day, FA$Electricity_bill_BDT, FA$Electricity_frequency)
  maint <- mapply(per_day, FA$Equipment_Cooler_Maintenance_BDT,
                  FA$Equipment_Cooler_Maintenance_frequency)
  wages <- as_num(FA$Workers_count) * as_num(FA$Worker_daily_wage_BDT)
  other <- mapply(per_day, FA$Other_cost_BDT, "Monthly")
  tot <- rent + elec + maint + wages + other
  data.frame(Stratum = "Aratdar", cap = cap, total = tot,
             stringsAsFactors = FALSE)
}
mc_bepari <- function() {
  cap <- as_num(FB$Daily_capacity_kg)
  period <- as_num(FB$Trip_frequency_days); period[is.na(period) | period <= 0] <- 1
  trips  <- as_num(FB$Trips_per_period);    trips[is.na(trips)] <- 0
  transport <- (as_num(FB$Transport_fare_per_trip_BDT) +
                  as_num(FB$Loading_Unloading_cost_per_trip_BDT)) * trips / period
  ice  <- as_num(FB$Ice_cost_BDT_per_day); ice[is.na(ice)] <- 0
  buy  <- sapply(as.character(FB$Respondent_ID), resp_buy_px)
  buy[is.na(buy)] <- 0
  unit <- tolower(as.character(FB$Commission_unit))
  cval <- as_num(FB$Commission_to_aratdar_value); cval[is.na(cval)] <- 0
  comm <- ifelse(grepl("^percent", unit), cval / 100 * buy * cap, cval * trips / period)
  loss <- as_num(FB$Transit_damage_pct) / 100 * buy * cap
  loss[is.na(loss)] <- 0
  data.frame(Stratum = "Bepari/Faria", cap = cap,
             total = transport + ice + comm + loss, stringsAsFactors = FALSE)
}
mc_retail <- function() {
  cap <- as_num(FR$Daily_capacity_kg)
  rent <- as_num(FR$Shop_Van_Rent_BDT_per_day); rent[is.na(rent)] <- 0
  ice  <- as_num(FR$Ice_cost_BDT_per_day);      ice[is.na(ice)] <- 0
  wash <- as_num(FR$Wash_Water_Other_cost_BDT_per_day); wash[is.na(wash)] <- 0
  buy  <- sapply(as.character(FR$Respondent_ID), resp_buy_px); buy[is.na(buy)] <- 0
  loss <- as_num(FR$Spoilage_pct) / 100 * buy * cap; loss[is.na(loss)] <- 0
  data.frame(Stratum = "Khuchra retailer", cap = cap, total = rent + ice + wash + loss,
             stringsAsFactors = FALSE)
}
mc_all <- rbind(mc_aratdar(), mc_bepari(), mc_retail())
mc_all <- mc_all[!is.na(mc_all$cap) & mc_all$cap > 0, , drop = FALSE]
mc_all$per_kg <- mc_all$total / mc_all$cap
T4b <- do.call(rbind, lapply(split(mc_all, mc_all$Stratum), function(g)
  data.frame(Stratum = g$Stratum[1], n = nrow(g),
             MC_BDT_kg_mean = round(mean(g$per_kg), 2),
             MC_BDT_kg_sd = round(sd(g$per_kg), 2),
             MC_BDT_kg_median = round(median(g$per_kg), 2),
             MC_BDT_kg_min = round(min(g$per_kg), 2),
             MC_BDT_kg_max = round(max(g$per_kg), 2),
             Throughput_kg_day_mean = round(mean(g$cap), 2),
             stringsAsFactors = FALSE)))
rownames(T4b) <- NULL
SUM_MC <- sum(T4b$MC_BDT_kg_mean)
TABLES[["T4b_Marketing_Cost_per_kg"]] <- list(
  df = T4b, title = "Table 4b. Marketing cost per kilogram by trader stratum",
  note = paste0("Methodology 3.7.1 eq. 3.3. Mixed-frequency items converted to BDT per trading ",
    "day (", TRADING_DAYS_MONTH, "/month, ", TRADING_DAYS_YEAR, "/year); trips annualised over ",
    "Trip_frequency_days; Form A 'Other cost' treated as monthly. Physical losses (retailer ",
    "spoilage, bepari transit damage) valued at the respondent's own mean purchase price. ",
    "Aratdar commission is income to the aratdar and is excluded from his MC."))

## ============================ T5  Payment methods ============================
pay_row <- function(label, rs) data.frame(
  Cash_pct_mean = round(mean(as_num(rs$Payment_cash_pct), na.rm = TRUE), 2),
  MFS_pct_mean  = round(mean(as_num(rs$Payment_MFS_pct), na.rm = TRUE), 2),
  Credit_pct_mean = round(mean(as_num(rs$Payment_credit_pct), na.rm = TRUE), 2),
  MFS_Regular_n = sum(as.character(rs$MFS_transaction_frequency) == "Regular"),
  MFS_Occasional_n = sum(as.character(rs$MFS_transaction_frequency) == "Occasional"),
  MFS_Never_n = sum(as.character(rs$MFS_transaction_frequency) == "Never"),
  Payment_method = "", Payment_method_pct = NA_real_, Actor = label, n = nrow(rs),
  stringsAsFactors = FALSE)
T5 <- rbind(pay_row("Aratdar", FA), pay_row("Bepari/Faria", FB), pay_row("Retailer", FR))
cpay0 <- table(as.character(FC$Payment_method))
cpay  <- cpay0[order(-as.integer(cpay0))]          ## most frequent first
for (m in names(cpay))
  T5 <- rbind(T5, data.frame(Cash_pct_mean = NA, MFS_pct_mean = NA, Credit_pct_mean = NA,
    MFS_Regular_n = NA, MFS_Occasional_n = NA, MFS_Never_n = NA,
    Payment_method = m, Payment_method_pct = pct(as.integer(cpay[[m]]), nrow(FC)),
    Actor = "Consumer (Form C)", n = nrow(FC), stringsAsFactors = FALSE))
TABLES[["T5_Payment_Methods"]] <- list(
  df = T5, title = "Table 5. Payment methods by actor",
  note = "Trader rows: mean share of receipts by mode plus MFS-use frequency counts. Consumer rows: share of transactions by mode.")

## ============================ T6  Marketing problems =========================
probs <- sort(unique(unlist(lapply(list(FA, FB, FR),
        function(d) as.character(d$Problem_1)))))
for (k in 2:3) probs <- union(probs, unique(unlist(lapply(list(FA, FB, FR),
        function(d) as.character(d[[paste0("Problem_", k)]])))))
probs <- sort(probs[!is.na(probs) & probs != ""])
cnt <- function(d, p) sum(as.character(d$Problem_1) == p) +
                      sum(as.character(d$Problem_2) == p) +
                      sum(as.character(d$Problem_3) == p)
T6 <- do.call(rbind, lapply(probs, function(p) data.frame(
  Problem = p, Aratdar_n = cnt(FA, p), Aratdar_pct = pct(cnt(FA, p), nrow(FA)),
  Bepari_n = cnt(FB, p), Bepari_pct = pct(cnt(FB, p), nrow(FB)),
  Retailer_n = cnt(FR, p), Retailer_pct = pct(cnt(FR, p), nrow(FR)),
  Total_n = cnt(FA, p) + cnt(FB, p) + cnt(FR, p),
  Total_pct = pct(cnt(FA, p) + cnt(FB, p) + cnt(FR, p), nrow(FA) + nrow(FB) + nrow(FR)),
  stringsAsFactors = FALSE)))
T6 <- T6[order(-T6$Total_n, T6$Problem), ]; rownames(T6) <- NULL
TABLES[["T6_Problems"]] <- list(
  df = T6, title = "Table 6. Marketing problems reported by traders",
  note = paste0("Each trader named up to three problems. Percentages are the share of the ",
    "90 traders who named the item (not a share of all mentions)."))

## ============================ T7  Market infrastructure ======================
T7_RENAME <- c(Market = "Market", Market_name = "Market_name", Obs_Date = "Obs_date",
               Market_type = "Type", Trading_hours = "Trading_hours",
               Retail_stall_count = "Retail_stalls",
               Transport_access = "Transport_access",
               Platform_condition = "Platform", Roofing = "Roofing",
               Drainage = "Drainage", Electricity = "Electricity",
               Ice_availability = "Ice", Sanitation = "Sanitation",
               Water_supply = "Water_supply", Fee_arrangement = "Fee_arrangement",
               Fee_rate_note = "Fee_rate_note", GPS_coordinates = "GPS")
T7_COLS <- names(T7_RENAME)
T7 <- as.data.frame(lapply(FM, function(x)
  if (inherits(x, "POSIXt") || inherits(x, "Date")) format(x, "%d/%m/%Y") else x),
  stringsAsFactors = FALSE)
T7 <- T7[, intersect(T7_COLS, names(T7)), drop = FALSE]
names(T7) <- T7_RENAME[names(T7)]
TABLES[["T7_Market_Infrastructure"]] <- list(
  df = T7, title = "Table 7. Observed market infrastructure (Form M)",
  note = "One structured observation per market; graded facility checklist.")

## ============================ T8  Consumer behaviour =========================
tab_rows <- function(field) {
  tb <- sort(table(as.character(FC[[field]])), decreasing = TRUE)
  do.call(rbind, lapply(names(tb), function(v) data.frame(
    Item = field, Value = v, n = as.integer(tb[[v]]),
    pct = pct(as.integer(tb[[v]]), nrow(FC)), stringsAsFactors = FALSE)))
}
T8 <- rbind(tab_rows("Visit_frequency"), tab_rows("Payment_method"),
            tab_rows("Main_reason_choosing_arat"))
T8$Item <- ifelse(T8$Item == "Visit_frequency", "Visit frequency",
           ifelse(T8$Item == "Payment_method",  "Payment method", T8$Item))
T8$Item[T8$Item == "Main_reason_choosing_arat"] <- "Main reason for choosing seller"
T8 <- rbind(T8, data.frame(Item = "Mean visit interval (days)",
  Value = round(mean(as_num(FC$Visit_interval_days), na.rm = TRUE), 2),
  n = nrow(FC), pct = NA, stringsAsFactors = FALSE))
## denominator = every focal-species row (66), matching the Python table
src <- most_common(CPF$Bought_from)
for (i in seq_along(src$keys)) T8 <- rbind(T8, data.frame(
  Item = "Focal purchase source (per purchase)", Value = src$keys[i],
  n = src$n[i], pct = pct(src$n[i], nrow(CPF)), stringsAsFactors = FALSE))
T8 <- rbind(T8, data.frame(Item = "Mean focal-species price paid (BDT/kg)",
  Value = round(mean(CPFY$price_kg, na.rm = TRUE), 2), n = sum(!is.na(CPFY$price_kg)),
  pct = NA, stringsAsFactors = FALSE))
T8 <- rbind(T8, data.frame(Item = "Mean purchase size (kg)",
  Value = round(mean(CPFY$qty_kg, na.rm = TRUE), 2), n = sum(!is.na(CPFY$qty_kg)),
  pct = NA, stringsAsFactors = FALSE))
TABLES[["T8_Consumer_Behaviour"]] <- list(
  df = T8, title = "Table 8. Consumer purchasing behaviour",
  note = "Exit-intercepted consumers (n=30). Focal-purchase rows are per purchase record.")

## ============================ T9  Other aquatic products =====================
mc9 <- most_common(COF$Fish_name_local)
T9 <- do.call(rbind, lapply(mc9$keys, function(nm) {
  g <- COF[as.character(COF$Fish_name_local) == nm, , drop = FALSE]
  data.frame(`Fish (local name)` = nm, n = nrow(g),
             Mean_price_BDT_kg = round(mean(g$price_kg, na.rm = TRUE), 2),
             Mean_qty_kg = round(mean(as_num(g$Quantity_raw), na.rm = TRUE), 2),
             check.names = FALSE, stringsAsFactors = FALSE)
}))
rownames(T9) <- NULL
TABLES[["T9_Other_Fish"]] <- list(
  df = T9, title = "Table 9. Other aquatic products purchased by consumers",
  note = "Non-focal items, including crustaceans; n is often 1-3, so means are indicative only.")

## ============================ T10 Margins / producer share ===================
chain_codes <- T3$Species_code[!is.na(T3$Total_spread_BDT_kg) &
                                T3$Species_code != "ALL"]
sp_mean_over <- function(actor, field, markets = NULL)
  round(mean(sapply(chain_codes, function(c) po_mean(actor, field, c, markets))), 2)
prod10 <- sp_mean_over("Aratdar", "buy_kg", LANDING)
arat10 <- sp_mean_over("Aratdar", "sell_kg", LANDING)
bep10  <- sp_mean_over("Bepari_Faria", "sell_kg")
cons10 <- round(mean(sapply(chain_codes, cons_mean)), 2)
lvl <- function(name, sell, buy, ns) data.frame(
  Level = name, n_species = ns, Margin_BDT_kg = round(sell - buy, 2),
  Margin_pct_consumer = round(100 * (sell - buy) / cons10, 1), stringsAsFactors = FALSE)
T10 <- rbind(
  lvl("Aratdar (auction margin, M1/M6)", arat10, prod10, length(chain_codes)),
  lvl("Bepari/Faria (wholesale margin)", bep10, arat10, length(chain_codes)),
  lvl("Retailer (margin to consumer)", cons10, bep10, length(chain_codes)),
  data.frame(Level = "Total marketing spread (consumer - producer)",
             n_species = length(chain_codes),
             Margin_BDT_kg = round(cons10 - prod10, 2),
             Margin_pct_consumer = round(100 - 100 * prod10 / cons10, 1),
             stringsAsFactors = FALSE),
  data.frame(Level = "Producer share of consumer price",
             n_species = length(chain_codes), Margin_BDT_kg = NA,
             Margin_pct_consumer = round(100 * prod10 / cons10, 1),
             stringsAsFactors = FALSE))
TABLES[["T10_Margin_Summary"]] <- list(
  df = T10, title = "Table 10. Channel margins and producer's share",
  note = paste0("Unweighted means of species-level means over the ", length(chain_codes),
    " chain-complete species. Margins are differences of consecutive level means, so they sum ",
    "to the total spread and PS% + spread% = 100."))

## ============================ T11 Retail price by market ======================
T11 <- do.call(rbind, lapply(SP_CODES, function(code) {
  row <- data.frame(Species = paste(code, SP_LOCAL[[code]]), stringsAsFactors = FALSE)
  for (m in MK_CODES) {
    v <- PO$sell_kg[PO$Actor_type == "Khuchra" &
                      as.character(PO$Species_code) == code &
                      as.character(PO$Market) == m]
    v <- v[!is.na(v)]
    row[[MK_NAME[[m]]]] <- if (length(v)) round(mean(v), 0) else NA_real_
  }
  row
}))
TABLES[["T11_Retail_Price_by_Market"]] <- list(
  df = T11, title = "Table 11. Retail prices by species and market (BDT/kg)",
  note = "Mean retailer (khuchra) selling price by market. Blank = not observed.")

## ============================ T12/12b Matched pairs ==========================
pr <- PO[!is.na(PO$Pair_ID) & as.character(PO$Pair_ID) != "", , drop = FALSE]
ACTOR_ORDER <- c(Aratdar = 0, Bepari_Faria = 1, Khuchra = 2)
if (nrow(pr)) {
  pr$pair <- as.character(pr$Pair_ID)
  groups  <- split(seq_len(nrow(pr)), pr$pair)
  T12 <- do.call(rbind, lapply(names(groups), function(pid) {
    ix <- groups[[pid]]; g <- pr[ix, , drop = FALSE]
    best <- NULL
    if (nrow(g) >= 2) for (a in seq_len(nrow(g))) for (b in seq_len(nrow(g))) {
      if (a == b) next
      sa <- g[a, ]; bb <- g[b, ]
      if (is.na(sa$sell_kg) || is.na(bb$buy_kg)) next
      ra <- ACTOR_ORDER[[as.character(sa$Actor_type)]]; if (is.na(ra)) ra <- 9
      rb <- ACTOR_ORDER[[as.character(bb$Actor_type)]]; if (is.na(rb)) rb <- 9
      if (ra > rb) next                       ## buyer cannot sit upstream of the seller
      d <- abs(sa$sell_kg - bb$buy_kg)
      if (is.null(best) || d < best$d)
        best <- list(d = d, sa = sa, bb = bb)
    }
    if (is.null(best)) return(data.frame(
      Pair_ID = pid, Market = as.character(g$Market[1]),
      Species_code = as.character(g$Species_code[1]),
      Seller_ID = NA, Seller_actor = NA, Seller_sell_BDT_kg = NA,
      Buyer_ID = NA, Buyer_actor = NA, Buyer_buy_BDT_kg = NA,
      Diff_BDT_kg = NA, Complete = "False", stringsAsFactors = FALSE))
    data.frame(Pair_ID = pid,
      Market = as.character(best$sa$Market %||% best$bb$Market),
      Species_code = as.character(best$sa$Species_code),
      Seller_ID = as.character(best$sa$Respondent_ID),
      Seller_actor = as.character(best$sa$Actor_type),
      Seller_sell_BDT_kg = round(best$sa$sell_kg, 2),
      Buyer_ID = as.character(best$bb$Respondent_ID),
      Buyer_actor = as.character(best$bb$Actor_type),
      Buyer_buy_BDT_kg = round(best$bb$buy_kg, 2),
      Diff_BDT_kg = round(best$sa$sell_kg - best$bb$buy_kg, 2),
      Complete = "True", stringsAsFactors = FALSE)
  }))
  rownames(T12) <- NULL
  use <- T12[!is.na(T12$Diff_BDT_kg), , drop = FALSE]
  d <- use$Diff_BDT_kg
  nz <- d[d != 0]                              ## zeros dropped, exact test on the rest
  wt <- if (length(nz) >= 5) suppressWarnings(wilcox.test(nz, exact = TRUE,
                                                          conf.int = FALSE)) else NULL
  W <- if (!is.null(wt)) as.numeric(wt$statistic) else NA_real_
  p <- if (!is.null(wt)) as.numeric(wt$p.value) else NA_real_
  T12b <- data.frame(Item = c("Usable matched pairs (n)", "Pairs with non-zero difference",
                              "Median difference (BDT/kg)", "Mean difference (BDT/kg)",
                              "Wilcoxon W statistic", "p-value (two-sided)", "Interpretation"),
    Value = c(nrow(use), length(nz), median(d), round(mean(d), 2), W,
              if (is.na(p)) NA else round(p, 4),
              if (is.na(p)) "insufficient non-zero pairs" else
              ifelse(p >= ALPHA,
                "p >= 0.05: seller-sell and buyer-buy quotes of matched lots do not differ systematically - self-reported chain prices are internally consistent",
                "p < 0.05: systematic disagreement between matched quotes")),
    stringsAsFactors = FALSE)
} else {
  T12  <- data.frame(Pair_ID = character(0))
  T12b <- data.frame(Item = "no pairs", Value = "n/a")
}
TABLES[["T12_Pair_Detail"]] <- list(df = T12,
  title = "Table 12. Matched buyer-seller pair detail",
  note = paste0("Methodology 3.3.4. For each Pair_ID the best (seller, buyer) row pair is ",
    "chosen subject to the seller sitting upstream of the buyer, minimising |sell - buy|."))
TABLES[["T12b_Wilcoxon_Result"]] <- list(df = T12b,
  title = "Table 12b. Wilcoxon signed-rank test on matched pairs",
  note = "Consistency diagnostic on matched lots; zero differences dropped, exact test.")

## ============================ T13 Species x market ===========================
T13 <- do.call(rbind, lapply(SP_CODES, function(code) do.call(rbind,
  lapply(MK_CODES, function(m) {
    w <- PO[PO$Actor_type == "Bepari_Faria" & as.character(PO$Species_code) == code &
              as.character(PO$Market) == m & !is.na(PO$sell_kg), , drop = FALSE]
    r <- PO[PO$Actor_type == "Khuchra" & as.character(PO$Species_code) == code &
              as.character(PO$Market) == m & !is.na(PO$sell_kg), , drop = FALSE]
    c0 <- CPFY[as.character(CPFY$Species_code) == code & as.character(CPFY$Market) == m &
                 !is.na(CPFY$price_kg), , drop = FALSE]
    wm <- if (nrow(w)) mean(w$sell_kg) else NA_real_
    rm_ <- if (nrow(r)) mean(r$sell_kg) else NA_real_
    cm <- if (nrow(c0)) mean(c0$price_kg) else NA_real_
    data.frame(Species = code, Market = m,
      Wholesale_sell_mean = if (is.na(wm)) NA else round(wm, 2), n_wholesale = nrow(w),
      Retailer_sell_quote_mean = if (is.na(rm_)) NA else round(rm_, 2), n_retailer = nrow(r),
      Consumer_paid_mean = if (is.na(cm)) NA else round(cm, 2), n_consumer = nrow(c0),
      Retail_margin_quote_BDT_kg = if (is.na(rm_) || is.na(wm)) NA else round(rm_ - wm, 2),
      Retail_margin_paid_BDT_kg  = if (is.na(cm) || is.na(wm)) NA else round(cm - wm, 2),
      stringsAsFactors = FALSE)
  }))))
rownames(T13) <- NULL
TABLES[["T13_Species_Market_Spread"]] <- list(
  df = T13, title = "Table 13. Wholesale-retail-consumer prices by species and market",
  note = "Within-market decomposition; margins here are computed inside each market cell and therefore avoid the composition effects of pooled means.")

## ============================ T14 Kruskal-Wallis =============================
kw_rows <- list()
for (code in SP_CODES) {
  cells <- list(); sizes <- c()
  for (m in MK_CODES) {
    v <- PO$sell_kg[PO$Actor_type == "Khuchra" &
                      as.character(PO$Species_code) == code &
                      as.character(PO$Market) == m]
    v <- v[!is.na(v)]
    if (length(v) >= MIN_CONS) { cells[[m]] <- v; sizes[m] <- length(v) }
  }
  if (length(cells) >= MIN_MARKETS) {
    kt <- kruskal.test(cells)
    kw_rows[[code]] <- data.frame(Species = code, Local_name = SP_LOCAL[[code]],
      Test_tier = sprintf("exploratory (n>=%d)", MIN_CONS),
      Markets_qualifying = paste(names(cells), collapse = "; "),
      n_per_market = paste(sprintf("%s=%d", names(cells), sizes), collapse = "; "),
      H = round(as.numeric(kt$statistic), 3), df = as.numeric(kt$parameter),
      p_value = round(as.numeric(kt$p.value), 4),
      Decision = ifelse(as.numeric(kt$p.value) < ALPHA,
        "reject H0 (p<0.05): prices differ across markets",
        "fail to reject H0 (p>=0.05)"), stringsAsFactors = FALSE)
  } else {
    kw_rows[[code]] <- data.frame(Species = code, Local_name = SP_LOCAL[[code]],
      Test_tier = "not run", Markets_qualifying = "", n_per_market = "",
      H = NA, df = NA, p_value = NA,
      Decision = sprintf("cells < n threshold in <%d markets -> descriptive only", MIN_MARKETS),
      stringsAsFactors = FALSE)
  }
}
T14 <- do.call(rbind, kw_rows); rownames(T14) <- NULL
TABLES[["T14_Species_Market_KruskalWallis"]] <- list(
  df = T14, title = "Table 14. Kruskal-Wallis test of retail price across markets",
  note = paste0("Methodology 3.8 pre-registers n>=5 per cell; the 5-respondents-per-cell design ",
    "cannot reach that, so tests are run at an explicitly labelled exploratory threshold of n>=",
    MIN_CONS, " in >=", MIN_MARKETS, " markets and reported as exploratory."))

## ============================ T14b Dunn post-hoc (Holm) ======================
dunn_rows <- list()
for (code in SP_CODES) {
  cells <- list()
  for (m in MK_CODES) {
    v <- PO$sell_kg[PO$Actor_type == "Khuchra" &
                      as.character(PO$Species_code) == code &
                      as.character(PO$Market) == m]
    v <- v[!is.na(v)]
    if (length(v) >= MIN_CONS) cells[[m]] <- v
  }
  if (length(cells) < MIN_MARKETS) next
  ## Methodology: pairwise contrasts follow a rejected omnibus null only.
  kwp <- T14$p_value[T14$Species == code]
  if (length(kwp) == 0 || is.na(kwp) || kwp >= ALPHA) next
  allv <- unlist(cells)
  N <- length(allv); r <- rank(allv)
  tie <- sum(tapply(r, allv, function(g) length(g)^3 - length(g)))
  A <- N * (N + 1) / 12 * (1 - tie / (N^3 - N))
  mr <- tapply(r, rep(names(cells), sapply(cells, length)), mean)
  ns <- sapply(cells, length)
  ms <- names(cells)
  if (length(ms) < 2) next
  for (i in 1:(length(ms) - 1)) for (j in (i + 1):length(ms)) {
    se <- sqrt(A * (1 / ns[ms[i]] + 1 / ns[ms[j]]))
    z <- (mr[[ms[i]]] - mr[[ms[j]]]) / se
    dunn_rows[[length(dunn_rows) + 1]] <- data.frame(
      Market_i = ms[i], Market_j = ms[j], z = round(z, 3),
      raw_p = round(2 * pnorm(-abs(z)), 4), Species = code, stringsAsFactors = FALSE)
  }
}
T14b <- if (length(dunn_rows)) {
  d <- do.call(rbind, dunn_rows)
  d$p_holm <- NA_real_
  for (sp in unique(d$Species)) {
    ix <- which(d$Species == sp)
    d$p_holm[ix] <- round(p.adjust(d$raw_p[ix], method = "holm"), 4)
  }
  d$significant_0.05 <- ifelse(d$p_holm < ALPHA, "True", "False")
  d[order(d$Species, d$raw_p), c("Market_i", "Market_j", "z", "raw_p", "p_holm",
                                 "significant_0.05", "Species")]
} else data.frame(Market_i = character(0))
rownames(T14b) <- NULL
TABLES[["T14b_Dunn_Holm_Posthoc"]] <- list(
  df = T14b, title = "Table 14b. Dunn post-hoc with Holm adjustment",
  note = "Pairwise contrasts following significant Kruskal-Wallis tests; Holm step-down familywise control.")

## ============================ T15 Payment x actor chi-square =================
mfs_tab <- rbind(
  table(factor(as.character(FA$MFS_transaction_frequency),
               levels = c("Regular", "Occasional", "Never"))),
  table(factor(as.character(FB$MFS_transaction_frequency),
               levels = c("Regular", "Occasional", "Never"))),
  table(factor(as.character(FR$MFS_transaction_frequency),
               levels = c("Regular", "Occasional", "Never"))))
rownames(mfs_tab) <- c("Aratdar", "Bepari/Faria", "Retailer")
cs  <- suppressWarnings(chisq.test(mfs_tab))
n   <- sum(mfs_tab); E <- outer(rowSums(mfs_tab), colSums(mfs_tab)) / n
g   <- 2 * sum(ifelse(mfs_tab > 0, mfs_tab * log(mfs_tab / E), 0))
g_p <- pchisq(g, df = cs$parameter, lower.tail = FALSE)
fish_p <- tryCatch(suppressWarnings(fisher.test(mfs_tab, simulate.p.value = TRUE,
                                                B = 100000))$p.value,
                   error = function(e) NA_real_)
V <- sqrt(as.numeric(cs$statistic) / (n * (min(dim(mfs_tab)) - 1)))
mfs_share <- round(100 * mfs_tab[, 1] / rowSums(mfs_tab), 1)
T15 <- data.frame(
  Actor = c(rownames(mfs_tab),
            "chi-square (actor x MFS frequency)",
            "Cramer's V / smallest expected count"),
  n = c(rowSums(mfs_tab), n, NA),
  MFS_Regular = c(mfs_tab[, 1], NA, NA),
  MFS_Occasional = c(mfs_tab[, 2], NA, NA),
  MFS_Never = c(mfs_tab[, 3], NA, NA),
  MFS_share_pct = c(mfs_share,
    sprintf("chi2=%.2f, df=%d, p=%.4f, G-test p=%.4f, Fisher-exact p=%.4f",
            as.numeric(cs$statistic), as.numeric(cs$parameter), cs$p.value, g_p, fish_p),
    sprintf("V=%.3f / min exp=%.2f", V, min(E))),
  stringsAsFactors = FALSE)

TABLES[["T15_Payment_Actor_ChiSquare"]] <- list(
  df = T15, title = "Table 15. MFS adoption frequency by actor class",
  note = paste0("Chi-square of MFS-use frequency against actor class. The smallest expected ",
    "count is below 5, so the exact test is reported alongside Pearson and the likelihood-ratio ",
    "(G) test. The exact p is a Monte-Carlo estimate (B = 100,000) and may differ from the ",
    "Python engine in the third decimal; all three tests agree on the conclusion."))

## ============================ T16 Stratum margins (MWU) ======================
resp_margins <- function(actor) {
  d <- PO[PO$Actor_type == actor & !is.na(PO$buy_kg) & !is.na(PO$sell_kg), , drop = FALSE]
  g <- split(d, as.character(d$Respondent_ID))
  v <- vapply(g, function(x) mean(x$sell_kg - x$buy_kg), numeric(1))
  v[!is.na(v)]
}
mA <- resp_margins("Aratdar"); mB <- resp_margins("Bepari_Faria")
mR <- resp_margins("Khuchra")
iqr <- function(x) round(as.numeric(diff(quantile(x, c(.25, .75)))), 2)
T16 <- rbind(
  data.frame(Actor = "Aratdar", n = length(mA),
             Median_margin_BDT_kg = round(median(mA), 2), IQR_BDT_kg = iqr(mA),
             Mean_margin_BDT_kg = round(mean(mA), 2), stringsAsFactors = FALSE),
  data.frame(Actor = "Bepari_Faria", n = length(mB),
             Median_margin_BDT_kg = round(median(mB), 2), IQR_BDT_kg = iqr(mB),
             Mean_margin_BDT_kg = round(mean(mB), 2), stringsAsFactors = FALSE),
  data.frame(Actor = "Khuchra", n = length(mR),
             Median_margin_BDT_kg = round(median(mR), 2), IQR_BDT_kg = iqr(mR),
             Mean_margin_BDT_kg = round(mean(mR), 2), stringsAsFactors = FALSE))
## NB: use list(), not c() - c() would coerce the numeric vectors to character
pairs16 <- list(list("Aratdar", "Bepari_Faria", mA, mB),
                list("Aratdar", "Khuchra", mA, mR),
                list("Bepari_Faria", "Khuchra", mB, mR))
for (pr2 in pairs16) {
  u <- suppressWarnings(wilcox.test(pr2[[3]], pr2[[4]], exact = FALSE))
  T16 <- rbind(T16, data.frame(
    Actor = sprintf("Mann-Whitney U: %s vs %s", pr2[1], pr2[2]),
    n = sprintf("%d/%d", length(pr2[[3]]), length(pr2[[4]])),
    Median_margin_BDT_kg = NA, IQR_BDT_kg = NA,
    Mean_margin_BDT_kg = ifelse(u$p.value < 0.0001,
      sprintf("U=%.0f, p<0.0001", as.numeric(u$statistic)),
      sprintf("U=%.0f, p=%.4f", as.numeric(u$statistic), u$p.value)),
    stringsAsFactors = FALSE))
}
TABLES[["T16_Stratum_Margin_MannWhitney"]] <- list(
  df = T16, title = "Table 16. Trader stratum margins and Mann-Whitney tests",
  note = paste0("Per-respondent mean own-quote margin (Methodology 3.7.2: M = Ps - Pb). ",
    "This measures a different thing from Table 10's channel-level differences of level ",
    "means (Methodology 3.7.3); see the chapter text for the reconciliation."))

## ============================ T17 Cost-profit (Spearman) =====================
rows17 <- list()
for (i in seq_len(nrow(FR))) {
  rid <- as.character(FR$Respondent_ID[i])
  if (!rid %in% names(mR)) next
  cap <- as_num(FR$Daily_capacity_kg[i])
  if (is.na(cap) || cap <= 0) next
  rent <- as_num(FR$Shop_Van_Rent_BDT_per_day[i]); if (is.na(rent)) rent <- 0
  ice  <- as_num(FR$Ice_cost_BDT_per_day[i]);      if (is.na(ice))  ice  <- 0
  wash <- as_num(FR$Wash_Water_Other_cost_BDT_per_day[i]); if (is.na(wash)) wash <- 0
  sp   <- as_num(FR$Spoilage_pct[i]); if (is.na(sp)) sp <- 0
  buyv <- PO$buy_kg[as.character(PO$Respondent_ID) == rid]
  buyv <- if (length(buyv) && any(!is.na(buyv))) mean(buyv, na.rm = TRUE) else 0
  spoil <- sp / 100 * buyv * cap
  mc <- (rent + ice + wash + spoil) / cap
  mg <- mR[[rid]]
  rows17[[length(rows17) + 1]] <- data.frame(
    Respondent_ID = rid, Market = as.character(FR$Market[i]),
    Mean_margin_BDT_kg = round(mg, 2), Buy_price_BDT_kg = round(buyv, 2),
    Spoilage_loss_BDT_kg = round(spoil / cap, 2), MC_BDT_kg = round(mc, 2),
    Net_profit_BDT_kg = round(mg - mc, 2),
    Net_profit_pct_of_margin = if (mg != 0) round(100 * (mg - mc) / mg, 1) else NA,
    stringsAsFactors = FALSE)
}
T17 <- do.call(rbind, rows17); rownames(T17) <- NULL
if (nrow(T17) >= 8) {
  ct <- suppressWarnings(cor.test(T17$MC_BDT_kg, T17$Net_profit_BDT_kg, method = "spearman"))
  T17 <- rbind(T17, data.frame(Respondent_ID = "Spearman rho(MC, net margin)",
    Market = sprintf("n=%d", nrow(T17)), Mean_margin_BDT_kg = NA,
    Buy_price_BDT_kg = NA, Spoilage_loss_BDT_kg = NA,
    MC_BDT_kg = round(as.numeric(ct$estimate), 3),
    Net_profit_BDT_kg = round(ct$p.value, 4), Net_profit_pct_of_margin = NA,
    stringsAsFactors = FALSE))
}
TABLES[["T17_Retailer_MC_Profit_Spearman"]] <- list(
  df = T17, title = "Table 17. Retailer marketing cost and net profit (BDT/kg)",
  note = paste0("Methodology 3.7.1-3.7.2. MC/kg = (rent + ice + washing, BDT/day) plus the ",
    "spoilage loss valued at the respondent's own mean purchase price, divided by daily ",
    "capacity. Net profit = own-quote margin minus MC/kg. Spearman rho (Methodology 3.8 Q5)."))

## ============================ T18 Shapiro-Wilk ===============================
series <- list(
  "Producer price - landing markets M1/M6 (Form A buy)" =
    PO$buy_kg[PO$Actor_type == "Aratdar" & as.character(PO$Market) %in% LANDING],
  "Aratdar auction sell - M1/M6" =
    PO$sell_kg[PO$Actor_type == "Aratdar" & as.character(PO$Market) %in% LANDING],
  "Bepari/Faria sell - all markets" = PO$sell_kg[PO$Actor_type == "Bepari_Faria"],
  "Khuchra retailer sell quotes - all markets" = PO$sell_kg[PO$Actor_type == "Khuchra"],
  "Consumer-paid prices (Form C slips)" = CPFY$price_kg)
T18 <- do.call(rbind, lapply(names(series), function(nm) {
  v <- series[[nm]]; v <- v[!is.na(v)]
  if (length(v) < 3) return(data.frame(Series = nm, n = length(v), W = NA,
    p_value = NA, Decision = "n<3", stringsAsFactors = FALSE))
  sw <- shapiro.test(v)
  data.frame(Series = nm, n = length(v), W = round(as.numeric(sw$statistic), 4),
             p_value = signif(sw$p.value, 4),
             Decision = ifelse(sw$p.value <= ALPHA,
               "p<=0.05 - non-normal; nonparametric tests used",
               "p>0.05 - normal"),
             stringsAsFactors = FALSE)}))
TABLES[["T18_ShapiroWilk_Screening"]] <- list(
  df = T18, title = "Table 18. Shapiro-Wilk normality screening",
  note = "Normality screen applied before the inferential battery (Methodology 3.8).")

## ============================ T19 Channel indicators =========================
t19 <- do.call(rbind, lapply(chain_codes, function(c) {
  pp <- po_mean("Aratdar", "buy_kg", c, LANDING); cc <- cons_mean(c)
  sp <- cc - pp
  data.frame(Species_code = c, Local_name = SP_LOCAL[[c]],
    Producer_BDT_kg = pp, Consumer_BDT_kg = cc, Price_spread_BDT_kg = round(sp, 2),
    GMM_pct = round(100 * sp / cc, 1), SumMC_BDT_kg = round(SUM_MC, 2),
    NMM_pct = round(100 * (sp - SUM_MC) / cc, 1), PS_pct = round(100 * pp / cc, 1),
    ME_consumer = round(cc / (SUM_MC + sp), 3), ME_producer = round(pp / (SUM_MC + sp), 3),
    stringsAsFactors = FALSE)}))
pp_a <- round(mean(t19$Producer_BDT_kg), 2); cc_a <- round(mean(t19$Consumer_BDT_kg), 2)
sp_a <- round(cc_a - pp_a, 2)
wP <- wC <- 0
for (c in chain_codes) {
  q <- sum(CPFY$qty_kg[as.character(CPFY$Species_code) == c], na.rm = TRUE)
  if (q > 0) { wP <- wP + po_mean("Aratdar", "buy_kg", c, LANDING) * q
               wC <- wC + cons_mean(c) * q }
}
T19 <- rbind(t19, data.frame(
  Species_code = "ALL",
  Local_name = paste0("Mean of species means (chain-complete: ",
                      paste(chain_codes, collapse = ", "), ")"),
  Producer_BDT_kg = pp_a, Consumer_BDT_kg = cc_a, Price_spread_BDT_kg = sp_a,
  GMM_pct = round(100 * sp_a / cc_a, 1), SumMC_BDT_kg = round(SUM_MC, 2),
  NMM_pct = round(100 * (sp_a - SUM_MC) / cc_a, 1),
  PS_pct = round(100 * pp_a / cc_a, 1),
  ME_consumer = round(cc_a / (SUM_MC + sp_a), 3),
  ME_producer = round(pp_a / (SUM_MC + sp_a), 3), stringsAsFactors = FALSE))
if (wC > 0) T19 <- rbind(T19, data.frame(
  Species_code = "ALL (volume-weighted)",
  Local_name = "PS weighted by kg purchased (sensitivity check)",
  Producer_BDT_kg = NA, Consumer_BDT_kg = NA, Price_spread_BDT_kg = NA,
  GMM_pct = NA, SumMC_BDT_kg = round(SUM_MC, 2), NMM_pct = NA,
  PS_pct = round(100 * wP / wC, 1), ME_consumer = NA, ME_producer = NA,
  stringsAsFactors = FALSE))
TABLES[["T19_Chain_Indicators"]] <- list(
  df = T19, title = "Table 19. Channel-level marketing indicators",
  note = paste0("Methodology 3.7.3 eq. 3.6-3.9 and 3.7.4 eq. 3.10. GMM%=(Pr-Pp)/Pr; ",
    "NMM%=(Pr-Pp-SumMC)/Pr; PS%=Pp/Pr; ME_consumer=Pr/(SumMC+SumM) and ",
    "ME_producer=Pp/(SumMC+SumM) with SumM = the price spread. SumMC = ", round(SUM_MC, 2),
    " BDT/kg is chain-wide (Table 4b) and therefore constant across species."))

## ============================ WRITE OUTPUTS ==================================
mkdir(OUTPUT_DIR); mkdir(file.path(OUTPUT_DIR, "tables"))
if (MAKE_CHARTS) mkdir(file.path(OUTPUT_DIR, "charts"))

for (nm in names(TABLES)) {
  write.csv(TABLES[[nm]]$df, file.path(OUTPUT_DIR, "tables", paste0(nm, ".csv")),
            row.names = FALSE, fileEncoding = "UTF-8")
}
cat(sprintf("Wrote %d tables to %s/tables/\n", length(TABLES), OUTPUT_DIR))

## ------------------------------------------------------------------ CHARTS --
if (MAKE_CHARTS) {
  png1 <- function(f, w = 2400, h = 1600, res = 300)
    png(file.path(OUTPUT_DIR, "charts", f), width = w, height = h, res = res)
  ## C1 price chain
  d <- T3[T3$Species_code != "ALL", , drop = FALSE]
  d <- d[!is.na(d$Producer_BDT_kg), , drop = FALSE]
  png1("C1_price_chain_by_species.png")
  op <- par(mar = c(8, 5, 4, 2) + 0.1)
  cols <- c("#1f4e79", "#d9822b", "#2e8b57", "#c0504d", "#7b5ea7")
  m <- as.matrix(d[, c("Producer_BDT_kg", "Aratdar_sell_BDT_kg", "Bepari_sell_BDT_kg",
                       "Retailer_sell_BDT_kg", "Consumer_paid_BDT_kg")])
  barplot(t(m), beside = TRUE, col = cols, las = 2,
          main = "Price chain by species (BDT/kg)", ylab = "BDT per kg",
          names.arg = paste(d$Species_code, d$Local_name), cex.names = 0.7)
  legend("topleft", c("Producer", "Aratdar sell", "Bepari sell", "Retailer quote",
                      "Consumer paid"), fill = cols, bty = "n", cex = 0.8)
  par(op); dev.off()
  ## C2 producer share
  d2 <- T3[!is.na(T3$Producer_share_pct) & T3$Species_code != "ALL", , drop = FALSE]
  d2 <- d2[order(d2$Producer_share_pct), ]
  png1("C2_producers_share.png")
  op <- par(mar = c(6, 8, 4, 4) + 0.1)
  bp <- barplot(d2$Producer_share_pct, horiz = TRUE, col = "#1f4e79",
                names.arg = paste(d2$Species_code, d2$Local_name), las = 1,
                main = "Producer's share of consumer price (%)", xlim = c(0, 100))
  text(d2$Producer_share_pct + 2, bp, sprintf("%.1f%%", d2$Producer_share_pct), cex = 0.8)
  par(op); dev.off()
  ## C3 payment mix
  pm <- T5[!is.na(T5$Cash_pct_mean), ]
  png1("C3_payment_mix.png")
  op <- par(mar = c(6, 5, 4, 8) + 0.1)
  mm <- as.matrix(pm[, c("Cash_pct_mean", "MFS_pct_mean", "Credit_pct_mean")])
  barplot(t(mm), beside = FALSE, col = c("#1f4e79", "#2e8b57", "#d9822b"),
          names.arg = pm$Actor, las = 1, main = "Payment mode mix by actor (%)",
          ylab = "% of receipts")
  legend("topright", c("Cash", "MFS", "Credit"),
         fill = c("#1f4e79", "#2e8b57", "#d9822b"), bty = "n")
  par(op); dev.off()
  ## C4 education
  png1("C4_education.png")
  op <- par(mar = c(6, 5, 4, 8) + 0.1)
  ed <- T1[, c("Edu_Illiterate_pct", "Edu_Primary_pct", "Edu_Secondary_pct",
               "Edu_Higher Secondary_pct")]
  barplot(t(as.matrix(ed)), beside = TRUE, col = c("#c0504d", "#d9822b", "#2e8b57", "#1f4e79"),
          names.arg = T1$Actor, las = 2, main = "Education profile by actor (%)", ylab = "%")
  legend("topright", c("Illiterate", "Primary", "Secondary", "Higher secondary"),
         fill = c("#c0504d", "#d9822b", "#2e8b57", "#1f4e79"), bty = "n", cex = 0.8)
  par(op); dev.off()
  ## C5 problems
  png1("C5_problems.png")
  op <- par(mar = c(10, 5, 4, 2) + 0.1)
  barplot(T6$Total_pct, names.arg = T6$Problem, las = 2, col = "#7b5ea7",
          main = "Marketing problems (% of 90 traders)", ylab = "% of traders",
          cex.names = 0.7)
  par(op); dev.off()
  ## C7 daily capacity
  png1("C7_daily_capacity.png")
  op <- par(mar = c(6, 5, 4, 2) + 0.1)
  boxplot(split(mc_all$cap, mc_all$Stratum), las = 1, col = "#2e8b57",
          main = "Daily throughput by stratum", ylab = "kg per day")
  par(op); dev.off()
  cat("Wrote charts to ", OUTPUT_DIR, "/charts/\n", sep = "")
}

## --------------------------------------------------------------- EXCEL ------
wb <- openxlsx::createWorkbook()
addSheet <- function(name, tbl) {
  openxlsx::addWorksheet(wb, name)
  openxlsx::writeData(wb, name, tbl$title, startRow = 1)
  openxlsx::writeData(wb, name, tbl$df, startRow = 3)
  openxlsx::writeData(wb, name, paste("Note:", tbl$note),
                      startRow = nrow(tbl$df) + 5)
}
idx <- data.frame(Table = names(TABLES),
                  Title = sapply(TABLES, function(x) x$title),
                  Rows = sapply(TABLES, function(x) nrow(x$df)),
                  stringsAsFactors = FALSE)
addSheet("Index", list(df = idx, title = "MS-499 analysis — table index",
                       note = paste("Source workbook:", INPUT_FILE)))
for (nm in names(TABLES)) {
  sh <- substr(gsub("[^A-Za-z0-9_]", "", nm), 1, 31)
  addSheet(sh, TABLES[[nm]])
}
openxlsx::saveWorkbook(wb, file.path(OUTPUT_DIR, "R_Analysis_Summary.xlsx"),
                       overwrite = TRUE)
cat("Wrote", file.path(OUTPUT_DIR, "R_Analysis_Summary.xlsx"), "\n")

## ------------------------------------------------------------ QUALITY GATE --
ps <- T10$Margin_pct_consumer[T10$Level == "Producer share of consumer price"]
A <- T10$Margin_BDT_kg[1]; B <- T10$Margin_BDT_kg[2]; R <- T10$Margin_BDT_kg[3]
SP_ <- T10$Margin_BDT_kg[4]
cat("\n=== QUALITY GATES ===\n")
cat(sprintf("A+B+R = %.2f  vs spread = %.2f   [%s]\n", A + B + R, SP_,
            ifelse(abs((A + B + R) - SP_) < 0.05, "PASS", "FAIL")))
cat(sprintf("PS%% + spread%% = %.1f          [%s]\n",
            ps + T10$Margin_pct_consumer[4],
            ifelse(abs((ps + T10$Margin_pct_consumer[4]) - 100) < 0.15, "PASS", "FAIL")))
cat(sprintf("T3 ALL PS = %.1f  vs T10 PS = %.1f   [%s]\n",
            T3$Producer_share_pct[T3$Species_code == "ALL"], ps,
            ifelse(abs(T3$Producer_share_pct[T3$Species_code == "ALL"] - ps) < 0.05,
                   "PASS", "FAIL")))
cat(sprintf("Chain-complete species: %s\n", paste(chain_codes, collapse = ", ")))
## --------------------------------------------------------- VERIFICATION -----
gate <- function(ok) if (isTRUE(ok)) "PASS" else "FAIL"
GATES <- c(
  sum = abs((A + B + R) - SP_) < 0.05,
  pct = abs((ps + T10$Margin_pct_consumer[4]) - 100) < 0.15,
  psx = abs(T3$Producer_share_pct[T3$Species_code == "ALL"] - ps) < 0.05
)

hr <- strrep("=", 74)
cat("\n", hr, "\n", sep = "")
cat("VERIFICATION REPORT\n")
cat(hr, "\n")
cat("R version      : ", R.version.string, "\n", sep = "")
cat("Input workbook : ", basename(INPUT_FILE), "\n", sep = "")
cat("Output folder  : ", normalizePath(OUTPUT_DIR), "\n", sep = "")
cat("Data provenance: SYNTHETIC (pipeline-validation dataset, not field data)\n")

cat("\n-- Tables written ---------------------------------------------------------\n")
tf <- sort(list.files(file.path(OUTPUT_DIR, "tables"), pattern = "\\.csv$"))
nempty <- 0
for (f in tf) {
  d <- tryCatch(read.csv(file.path(OUTPUT_DIR, "tables", f), check.names = FALSE),
                error = function(e) NULL)
  ok <- !is.null(d) && nrow(d) > 0 && ncol(d) > 0
  if (!ok) nempty <- nempty + 1
  cat(sprintf("  %-36s %4d rows x %3d cols   %s\n",
              sub("\\.csv$", "", f), if (is.null(d)) 0 else nrow(d),
              if (is.null(d)) 0 else ncol(d),
              if (ok) "OK" else "<-- CHECK"))
}
cat(sprintf("  TOTAL: %d tables (%d with no data)\n", length(tf), nempty))

cat("\n-- Charts written ---------------------------------------------------------\n")
if (dir.exists(file.path(OUTPUT_DIR, "charts"))) {
  cf <- sort(list.files(file.path(OUTPUT_DIR, "charts"), pattern = "\\.png$"))
  cat("  ", paste(sub("\\.png$", "", cf), collapse = ", "), "\n", sep = "")
  cat(sprintf("  TOTAL: %d charts\n", length(cf)))
} else cat("  (none - MAKE_CHARTS = FALSE)\n")

cat("\n-- Headline figures (copy these into the paper) ---------------------------\n")
cat(sprintf("  Producer share (PS%%)            : %.1f %%\n", ps))
cat(sprintf("  Total price spread              : %.2f BDT/kg (%.1f %%)\n",
            SP_, T10$Margin_pct_consumer[4]))
cat(sprintf("  Aratdar / Bepari / Retailer     : %.2f / %.2f / %.2f BDT/kg\n", A, B, R))
cat(sprintf("  Gross / net marketing margin    : %.1f %% / %.1f %%\n",
            T19$GMM_pct[T19$Species_code == "ALL"], T19$NMM_pct[T19$Species_code == "ALL"]))
cat(sprintf("  Marketing efficiency (cons/prod): %.3f / %.3f\n",
            T19$ME_consumer[T19$Species_code == "ALL"],
            T19$ME_producer[T19$Species_code == "ALL"]))
cat(sprintf("  Chain-complete species          : %s\n",
            paste(chain_codes, collapse = ", ")))

cat("\n-- Reproducibility gates ---------------------------------------------------\n")
cat(sprintf("  [%s] segment margins telescope to the spread (%.2f vs %.2f)\n",
            gate(GATES["sum"]), A + B + R, SP_))
cat(sprintf("  [%s] producer share + spread = 100 (%.1f)\n",
            gate(GATES["pct"]), ps + T10$Margin_pct_consumer[4]))
cat(sprintf("  [%s] Table 3 pooled PS = Table 10 PS (%.1f vs %.1f)\n",
            gate(GATES["psx"]), T3$Producer_share_pct[T3$Species_code == "ALL"], ps))
cat(sprintf("  [%s] every table non-empty (%d of %d)\n",
            gate(nempty == 0), length(tf) - nempty, length(tf)))

allok <- all(GATES) && nempty == 0
cat("\n", hr, "\n", sep = "")
cat(sprintf("RESULT: %s  -- %d/%d tables written, %d/%d gates passed\n",
            if (allok) "ALL CHECKS PASSED" else "REVIEW NEEDED (see FAIL above)",
            length(tf) - nempty, length(tf), sum(GATES), length(GATES)))
cat(hr, "\n")
cat("\nDONE - outputs in ", normalizePath(OUTPUT_DIR), "/\n", sep = "")
